HL-75
horse-link/api.horse.link pull request #14
Opened 2022-11-02 06:58 UTC by xiangzhe0812

comment out sending eth and change to use correct wallet
![Screenshot 2022-11-02 at 4 52 58 pm](https://user-images.githubusercontent.com/1115763/199421222-feaf5637-caff-41dd-acd2-8be72a11e543.png)

2022-11-02 07:00 UTC, OptimusOpus submitted a review, later dismissed

2022-11-02 07:50 UTC, bitcoinbrisbane requested changes
Just cull the code.  No need to comment it out :)

2022-11-02 10:13 UTC, brettvniekerk submitted a review, later dismissed
LGTM just remove all the commented code

2022-11-02 23:41 UTC, brettvniekerk approved these changes

2022-11-02 23:46 UTC, bitcoinbrisbane approved these changes

2022-11-02 23:46 UTC, merged

2022-11-03 00:07 UTC, MikeyRobertson commented
Still getting network error
![image](https://user-images.githubusercontent.com/95732950/199624922-d2eb6c6a-41a4-4f0d-9c90-d35e2e3f1809.png)
Have received the 100 DIA, have received 0 ETH.