HL-181
horse-link/api.horse.link pull request #51
Opened 2022-11-25 02:43 UTC by bazmatic

https://dltx.atlassian.net/browse/HL-181

- Use Bytes16 for nonce, marketId, propositionId

2022-11-25 04:05 UTC, brettvniekerk requested changes
Can we merge this after the settling refactor is in, because the FE will need to be updated post-refactor to handle bytes16

2022-11-25 04:07 UTC, OptimusOpus approved these changes
LGTM

2022-11-25 05:19 UTC, pondpiu approved these changes

2022-11-27 23:42 UTC, OptimusOpus submitted a review, later dismissed

2022-11-27 23:48 UTC, pondpiu approved these changes

2022-11-28 05:22 UTC, pondpiu approved these changes

2022-11-28 05:30 UTC, OptimusOpus commented on src/index.js
> +  console.log(`Fetching meetings ${url}`);
Did you mean to leave this in?

2022-11-28 05:31 UTC, OptimusOpus commented on src/index.js
> +  console.log(req.url);
Did you mean to leave this in?

2022-11-28 05:32 UTC, OptimusOpus approved these changes
Just a few console.logs that I am not sure if you meant to leave. If they are meant to be there then I am happy to approve

2022-11-28 05:35 UTC, brettvniekerk approved these changes

2022-11-28 23:44 UTC, merged