HL-281 data provider
horse-link/api.horse.link pull request #77
Opened 2022-12-08 05:10 UTC by pondpiu

[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-281)

2022-12-08 06:56 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  for (let i = 0; i < Number(count); i++) {
perhaps this could be:
```ts
const marketAddresses = await Promise.all(
    Array.from(count).map((_, i) => registry.markets(i)
);
```

2022-12-08 06:57 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  await setCache("markets", marketAddresses, 60 * 60 * 24);
perhaps assign `60 * 60 * 24` to a descriptive var

2022-12-08 06:58 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  const cache = await getCache(`market-${address}`);
maybe `market-${address.toLowerCase()}` just in case

2022-12-08 07:01 UTC, brettvniekerk commented on src/providers/data/tokenDataProvider.ts
> +  const tokenAddresses = [];
perhaps:
```ts
const tokenAddresses = await Promise.all(
    vaultAddresses.map(async addr => {
        const contract = Vault__factory.connect(addr, wallet);
        return contract.asset();
    })
);
```

2022-12-08 07:01 UTC, brettvniekerk commented on src/providers/data/tokenDataProvider.ts
> +  await setCache("tokens", tokenAddresses, 60 * 60 * 24);
same here for descriptive var -- perhaps we should have a constants file that exports this value?

2022-12-08 07:02 UTC, brettvniekerk commented on src/providers/data/vaultDataProvider.ts
> +  const vaultAddresses = [];
perhaps:
```ts
const vaultAddresses = await Promise.all(
    Array.from(count).map(async (_, i) => registry.vaults(i))
);
```

2022-12-08 07:03 UTC, brettvniekerk commented on src/providers/data/vaultDataProvider.ts
> +  await setCache(`vault-${vaultAddress}-token`, vaultToken, 60);
same here

2022-12-08 07:04 UTC, brettvniekerk approved these changes
Overall LGTM - just needs some concurrency I think

2022-12-09 20:39 UTC, bitcoinbrisbane approved these changes

2022-12-09 20:40 UTC, bitcoinbrisbane requested changes
Meeting date provider missing the "r" on the fle name

2022-12-11 23:22 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  const marketContract = Market__factory.connect(marketAddress, wallet);
you could add the contract factories to a getter from `getContracts`:
```ts
const { getMarket } = await getContracts();
const marketContract = getMarket(address);
```

2022-12-11 23:22 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  const marketContract = Market__factory.connect(marketAddress, wallet);
or something along those lines

2022-12-11 23:22 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  const HOURS_TTL = 60 * 60;
should be in a `constants.ts` file i think

2022-12-11 23:23 UTC, brettvniekerk commented on src/providers/data/marketDataProvider.ts
> +  const vaultContract = Vault__factory.connect(vaultAddress, wallet);
like markets, same could be done with vaults here

2022-12-11 23:24 UTC, brettvniekerk commented on src/providers/data/tokenDataProvider.ts
> +  const HOURS_TTL = 60 * 60;
because this constant is re-used it should be in a `constants.ts` file

2022-12-11 23:25 UTC, brettvniekerk commented on src/providers/data/vaultDataProvider.ts
> +  const HOURS_TTL = 60 * 60;
same here

2022-12-11 23:27 UTC, brettvniekerk commented on src/providers/data/vaultDataProvider.ts
> +  const tokenContract = ERC20__factory.connect(tokenAddress, wallet);
erc20 factory could also be added to `getContracts`

2022-12-12 00:53 UTC, OptimusOpus approved these changes

2022-12-12 01:54 UTC, brettvniekerk commented on src/common/utils/contracts.ts
>  export const getContracts = async () => {
maybe this could be named `getProtocolContracts` if the others are exported separately

2022-12-12 03:05 UTC, merged