HL-281 test on CI
horse-link/api.horse.link pull request #88
Opened 2022-12-12 05:10 UTC by pondpiu

[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-281)

- GH action to run unit test on CI
- add typing to dataProviders

2022-12-12 05:35 UTC, OptimusOpus approved these changes

2022-12-12 06:05 UTC, brettvniekerk commented on package.json
> +    "test:unit": "mocha -r ts-node/register src/test/unit/*.spec.ts",
should these not run `codegen` beforehand too?

2022-12-12 06:07 UTC, brettvniekerk commented on src/common/cache.ts
>    return await nodeCache.get(key);
dont need `await` with async return statement

2022-12-12 06:09 UTC, brettvniekerk commented on src/common/cache.ts
> +export const setCache = async <T = any>(
why not just `<T>`?

2022-12-12 06:13 UTC, brettvniekerk commented on src/providers/data/runnerDataProvider.ts
> +  const cache = await getCache<Runners>(`race-${marketId}`);
`marketId.toLowerCase()` for safety pls

2022-12-12 06:13 UTC, brettvniekerk commented on src/providers/data/vaultDataProvider.ts
> +  const cache = await getCache<VaultToken>(`vault-${vaultCacheId}-token`);
`vaultCacheId.toLowerCase()` for safety pls

2022-12-12 06:14 UTC, brettvniekerk reviewed
Few minor things

2022-12-12 06:19 UTC, pondpiu commented on package.json
> +    "test:unit": "mocha -r ts-node/register src/test/unit/*.spec.ts",
i feel like its more ergonomic this way as i intend to use unit test to do TDD

2022-12-12 06:34 UTC, brettvniekerk submitted a review, later dismissed
LGTM - does everything still work with the `makeMarketId` change?

2022-12-12 06:45 UTC, brettvniekerk submitted a review, later dismissed
Pls test placing and settling bets before merging

2022-12-12 22:51 UTC, OptimusOpus approved these changes

2022-12-12 23:18 UTC, bitcoinbrisbane requested changes
Need to add REGISTERY_CONTRACT TO .env.development

2022-12-13 03:48 UTC, OptimusOpus approved these changes

2022-12-13 03:51 UTC, brettvniekerk approved these changes

2022-12-13 03:52 UTC, merged